"""Write soundboard/langnames_data.py: the name of every "Speak in" language, in every
app language, from Unicode CLDR (so nobody translates language names by hand).

Run it after adding a translate-xx add-on or an app language (assets/lang/*.json):

    .venv\\Scripts\\python scripts\\make_langnames.py

It reads the add-ons in modules/ and the catalogs in assets/lang/, fetches CLDR's
language/territory names from jsDelivr (a few seconds), and rewrites the data file.
"""
from __future__ import annotations

import json
import pprint
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CLDR = "https://cdn.jsdelivr.net/npm/cldr-localenames-full@46.0.0/main/{loc}/{what}.json"
OUT = ROOT / "soundboard" / "langnames_data.py"

# app language -> CLDR locale, where they differ
UI_TO_CLDR = {"zh-CN": "zh", "zh-TW": "zh-Hant", "pt-BR": "pt"}
# speak language -> CLDR language code, when CLDR names it better on its own
# (Traditional Chinese is named by script, not by country)
SPEAK_TO_CLDR = {"zh-TW": "zh-Hant", "nb": "no"}


def fetch(loc: str, what: str) -> dict:
    with urllib.request.urlopen(CLDR.format(loc=loc, what=what), timeout=30) as r:
        main = json.load(r)["main"]
    return next(iter(main.values()))["localeDisplayNames"]


def name_in(speak: str, langs: dict, regions: dict, pattern: str) -> str:
    """CLDR's own name; "Language (Country)" for a country, so both Portugueses sit
    together; Traditional Chinese by its script."""
    code = SPEAK_TO_CLDR.get(speak, speak)
    base, _, region = speak.partition("-")
    if code in langs and (code != speak or not region):   # not "Brazilian Portuguese":
        return langs[code]                                 # countries sort under their language
    if region and base in langs and region in regions:
        return pattern.replace("{0}", langs[base]).replace("{1}", regions[region])
    return langs[base]


def main() -> None:
    speak = sorted(json.loads(p.read_text(encoding="utf-8"))["language"]
                   for p in ROOT.glob("modules/translate-*/module.json"))
    ui = ["en"] + sorted(p.stem for p in (ROOT / "assets" / "lang").glob("*.json"))
    table: dict[str, dict[str, str]] = {}
    for lang in ui:
        loc = UI_TO_CLDR.get(lang, lang)
        names = fetch(loc, "languages")
        regions = fetch(loc, "territories")["territories"]
        pattern = fetch(loc, "localeDisplayNames")["localeDisplayPattern"]["localePattern"]
        # a menu item starts with a capital, even where CLDR writes "portugais"
        table[lang] = {s: (n := name_in(s, names["languages"], regions, pattern))[:1].upper()
                       + n[1:] for s in speak}
        print(lang, "ok")
    OUT.write_text(
        '"""Generated by scripts/make_langnames.py from Unicode CLDR 46 (Unicode License\n'
        'v3). Do not edit: rerun the script. App language -> speak language -> its name."""\n'
        f"NAMES = {pprint.pformat(table, width=100, sort_dicts=True)}\n", encoding="utf-8")
    print("wrote", OUT.relative_to(ROOT), len(ui), "app languages x", len(speak))


if __name__ == "__main__":
    main()
