"""Write the version resource for OnionBoard.exe (build.ps1 runs this before PyInstaller).

Windows reads an .exe's version info to name it: Windows Firewall's "has blocked some
features of …" prompt, Task Manager, the file's Properties → Details. Without it the
frozen app shows up as a bare file name. This writes PyInstaller's --version-file
from `soundboard.__version__`, so it never goes stale.

Usage: python scripts/version_info.py [out]   (default installer/version_info.txt)
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "installer" / "version_info.txt"
NAME = "Onion Board"
EXE = "OnionBoard.exe"
COPYRIGHT = "Copyright (C) Onion Board contributors"


def numbers(version: str) -> tuple[int, int, int, int]:
    """'1.6.5' -> (1, 6, 5, 0); a suffix like '1.7.0b1' keeps only the numbers."""
    parts = [int(p) for p in re.findall(r"\d+", version.split("+")[0])[:3]]
    if not parts:
        raise ValueError(f"no version number in {version!r}")
    return tuple(parts + [0] * (4 - len(parts)))   # type: ignore[return-value]


def render(version: str) -> str:
    """PyInstaller's version-file format (a VSVersionInfo expression)."""
    nums = numbers(version)
    strings = {
        "CompanyName": NAME,
        "FileDescription": NAME,
        "FileVersion": version,
        "InternalName": "OnionBoard",
        "LegalCopyright": COPYRIGHT,
        "OriginalFilename": EXE,
        "ProductName": NAME,
        "ProductVersion": version,
    }
    table = ",\n".join(f"          StringStruct({k!r}, {v!r})" for k, v in strings.items())
    return f"""# Generated by scripts/version_info.py from soundboard.__version__: don't edit.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={nums},
    prodvers={nums},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [
{table}
        ])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""


def main(argv: list[str]) -> int:
    sys.path.insert(0, str(ROOT))
    import soundboard
    out = Path(argv[0]) if argv else OUT
    out.write_text(render(soundboard.__version__), encoding="utf-8")
    print(f"{out}: {NAME} {soundboard.__version__}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
